export const items = [
  { id: 1, name: 'Thermometer', price: 250, imgPath: require("../../assets/thermometer.jpg"), gallery: [{ id: 1, imgPath: require("../../assets/thermometer.jpg") }, { id: 2, imgPath: require("../../assets/thermometer.jpg") }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
  { id: 2, name: 'Pen Knife ', price: 150, imgPath: require("../../assets/pen_knifes.jpeg"), gallery: [{ id: 1, imgPath: require('../../assets/pen_knifes.jpeg') }, { id: 2, imgPath: require('../../assets/pen_knifes.jpeg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 3, name: 'Sthethescope', price: 475, imgPath: require("../../assets/sthethescope.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/sthethescope.jpg') }, { id: 2, imgPath: require('../../assets/sthethescope.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 4, name: 'Artery Foreceps', price: 375, imgPath: require("../../assets/artery_foreceps.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/artery_foreceps.jpg') }, { id: 2, imgPath: require('../../assets/artery_foreceps.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 5, name: 'KN95 Mask', price: 100, imgPath: require("../../assets/KN95_mask.jpeg"), gallery: [{ id: 1, imgPath: require('../../assets/KN95_mask.jpeg') }, { id: 2, imgPath: require('../../assets/KN95_mask.jpeg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 6, name: 'Surgical Gloves', price: 90, imgPath: require("../../assets/surgical_gloves.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/surgical_gloves.jpg') }, { id: 2, imgPath: require('../../assets/surgical_gloves.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 7, name: 'Walking Crutches', price: 270, imgPath: require("../../assets/walking_crutches.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/walking_crutches.jpg') }, { id: 2, imgPath: require('../../assets/walking_crutches.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 8, name: 'Sphygmomanometer', price: 700, imgPath: require("../../assets/bp_monitor.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/bp_monitor.jpg') }, { id: 2, imgPath: require('../../assets/bp_monitor.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 9, name: 'Wheel Chair', price: 350, imgPath: require("../../assets/wheel_chair.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/wheel_chair.jpg') }, { id: 2, imgPath: require('../../assets/wheel_chair.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 10, name: 'Microscope', price: 900, imgPath: require("../../assets/microscope.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/microscope.jpg') }, { id: 2, imgPath: require('../../assets/microscope.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 11, name: 'Dental Chair', price: 400, imgPath: require("../../assets/dental_chair.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/dental_chair.jpg') }, { id: 2, imgPath: require('../../assets/dental_chair.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 12, name: 'Hygenic Tools', price: 150, imgPath: require("../../assets/hygenic_tools.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/hygenic_tools.jpg') }, { id: 2, imgPath: require('../../assets/hygenic_tools.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 13, name: 'Surgical Table', price: 550, imgPath: require("../../assets/surgical_table.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/surgical_table.jpg') }, { id: 2, imgPath: require('../../assets/surgical_table.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 14, name: 'Therapy Equipment', price: 750, imgPath: require("../../assets/therapy_equipment.jpg"), gallery: [{ id: 1, imgPath: require('../../assets/therapy_equipment.jpg') }, { id: 2, imgPath: require('../../assets/therapy_equipment.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' }
]
  
  