export const items = [
  { id: 1, name: "Artery Foreceps", price: 250, imgPath: require('../../assets/artery_foreceps.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') } ], desc: 'Curved-bladed mayo scissors allow deeper penetration into the wound than the type with straight blades. The scissors is made of stainless and blades are straight.', sold: 50, rating: 4.5, category: 'male' },
  { id: 2, name: "Pen Knife", price: 150, imgPath: require('../../assets/pen_knifes.jpeg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Detail Knife features our sharpest, most durable blade ever.', sold: 40, rating: 4.8, category: 'male' },
  { id: 4, name: "Thermometer", price: 350, imgPath: require('../../assets/thermometer.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 5, name: "KN95 Mask", price: 150, imgPath: require('../../assets/KN95_mask.jpeg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 6, name: "Surgical Gloves", price: 70, imgPath: require('../../assets/surgical_gloves.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 7, name: "Walking Crutches", price: 200, imgPath: require('../../assets/walking_crutches.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 8, name: "Blood Pressure Monitor", price: 350, imgPath: require('../../assets/bp_monitor.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 9, name: "Wheel Chair", price:560, imgPath: require('../../assets/wheel_chair.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 10, name: "Microscope", price: 900, imgPath: require('../../assets/microscope.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 11, name: "Dental Chair", price: 200, imgPath: require('../../assets/walking_crutches.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 12, name: "Hygenic Tools", price: 350, imgPath: require('../../assets/bp_monitor.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 13, name: "Surgical Table", price:560, imgPath: require('../../assets/wheel_chair.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 14, name: "Therapy Equipment", price: 900, imgPath: require('../../assets/microscope.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  
]
